services:
  students_db:
    container_name: collegedb
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: college 
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    container_name: college_server
    build:
      context: .
    environment:
      DB_HOST: students_db 
      NODE_ENV: production
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: college
      DB_PASS: password
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - students_db
